/** Domains and patterns for throwaway / 10-minute mail providers. */
const EXACT_DOMAINS = new Set([
  '10minutemail.com',
  '10minutemail.net',
  '10minutemail.org',
  '10minutemail.de',
  '10minmail.com',
  '10minmail.net',
  '20minutemail.com',
  '30minutemail.com',
  '60minutemail.com',
  'tempmail.com',
  'tempmail.net',
  'tempmail.org',
  'tempmail.de',
  'temp-mail.org',
  'temp-mail.io',
  'temp-mail.ru',
  'tempail.com',
  'tempinbox.com',
  'tempr.email',
  'tmpmail.net',
  'tmpmail.org',
  'tmpmail.com',
  'mailinator.com',
  'mailinator.net',
  'mailinator.org',
  'mailinator2.com',
  'guerrillamail.com',
  'guerrillamail.net',
  'guerrillamail.org',
  'guerrillamail.de',
  'guerrillamail.biz',
  'guerrillamailblock.com',
  'sharklasers.com',
  'grr.la',
  'pokemail.net',
  'spam4.me',
  'yopmail.com',
  'yopmail.fr',
  'yopmail.net',
  'cool.fr.nf',
  'jetable.fr.nf',
  'throwaway.email',
  'throwawaymail.com',
  'trashmail.com',
  'trashmail.net',
  'trashmail.org',
  'trashmail.de',
  'trashmail.me',
  'trashmail.at',
  'getnada.com',
  'nada.email',
  'dispostable.com',
  'maildrop.cc',
  'fakeinbox.com',
  'mintemail.com',
  'emailondeck.com',
  'mailnesia.com',
  'spamgourmet.com',
  'mytemp.email',
  'moakt.com',
  'inboxkitten.com',
  'getairmail.com',
  'mailcatch.com',
  'mailsac.com',
  'mail.tm',
  'mail.gw',
  'emailfake.com',
  'fakemailgenerator.com',
  'burnermail.io',
  'dropmail.me',
  'harakirimail.com',
  'mailpoof.com',
  'mohmal.com',
  'spambox.us',
  'spambog.com',
  'spambog.de',
  'spambog.ru',
  'mail-temporaire.fr',
  'courrieltemporaire.com',
  'minuteinbox.com',
  'inboxbear.com',
  'meltmail.com',
  'mailforspam.com',
  'spamfree24.org',
  'wegwerfemail.de',
  'wegwerfemail.net',
  'wegwerfemail.org',
  'wegwerfemailadresse.com',
  'einmalmail.de',
  'einrot.com',
  'mailslite.com',
  'luxusmail.org',
  'crazymailing.com',
  'tempsky.com',
  'emailnator.com',
  'generator.email',
  'mail7.io',
  'mailnesia.com',
  'mailnull.com',
  'mailscrap.com',
  'mailtemp.net',
  'mvrht.com',
  'nwldx.com',
  'objectmail.com',
  'proxymail.eu',
  'rcpt.at',
  'rhyta.com',
  's0ny.net',
  'safetymail.info',
  'shiftmail.com',
  'sneakemail.com',
  'spamavert.com',
  'spambox.info',
  'spamcero.com',
  'spamherelots.com',
  'spamspot.com',
  'superrito.com',
  'teleworm.us',
  'tempinbox.co.uk',
  'tmail.ws',
  'tmailinator.com',
  'trbvm.com',
  'tyldd.com',
  'uggsrock.com',
  'veryrealemail.com',
  'viditag.com',
  'viewcastmedia.com',
  'viewcastmedia.net',
  'viewcastmedia.org',
  'walala.org',
  'wuzup.net',
  'wuzupmail.net',
  'zoemail.org',
])

/** Subdomain roots — blocks user@xxx.mailinator.com etc. */
const ROOT_DOMAINS = [
  'mailinator.com',
  'guerrillamail.com',
  'guerrillamail.net',
  'guerrillamail.org',
  'guerrillamail.de',
  '10minutemail.com',
  '10minutemail.net',
  'tempmail.com',
  'temp-mail.org',
  'yopmail.com',
  'trashmail.com',
  'sharklasers.com',
  'maildrop.cc',
  'mailsac.com',
  'mail.tm',
]

const DOMAIN_KEYWORDS = [
  '10minutemail',
  '10minmail',
  'tempmail',
  'temp-mail',
  'tmpmail',
  'throwaway',
  'trashmail',
  'guerrillamail',
  'mailinator',
  'yopmail',
  'dispostable',
  'fakeinbox',
  'spamgourmet',
  'wegwerf',
  'einmalmail',
  'minuteinbox',
  'burnermail',
  'dropmail',
  'mohmal',
  'mailnesia',
  'getnada',
  'inboxkitten',
]

export function isDisposableEmailDomain(domain: string): boolean {
  const normalized = domain.trim().toLowerCase()
  if (!normalized) return false

  if (EXACT_DOMAINS.has(normalized)) return true

  for (const root of ROOT_DOMAINS) {
    if (normalized === root || normalized.endsWith(`.${root}`)) return true
  }

  for (const keyword of DOMAIN_KEYWORDS) {
    if (normalized.includes(keyword)) return true
  }

  return false
}
